"""change_model_inhert_from_db_model

Revision ID: 3acd4e6784d3
Revises: f7d34f3c7455
Create Date: 2018-09-07 12:31:42.492346

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import app.models

# revision identifiers, used by Alembic.
revision = '3acd4e6784d3'
down_revision = 'f7d34f3c7455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('openid', sa.String(length=64), nullable=False),
                    sa.Column('nick_name', sa.String(length=64), nullable=False),
                    sa.Column('gender', sa.Integer(), nullable=True),
                    sa.Column('city', sa.String(length=40), nullable=True),
                    sa.Column('province', sa.String(length=40), nullable=True),
                    sa.Column('country', sa.String(length=40), nullable=True),
                    sa.Column('avatarUrl', sa.String(length=200), nullable=True),
                    sa.Column('cashbox', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('openid')
                    )
    op.create_table('Order',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('total_price', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('ref_customer_id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.Column('discount', sa.Float(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['ref_customer_id'], ['Customer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Restaurant',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('ref_boss_id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('introduction', sa.Text(), nullable=True),
                    sa.Column('address', sa.String(length=64), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['ref_boss_id'], ['Boss.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Food',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('price', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('ref_restaurant_id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['ref_restaurant_id'], ['Restaurant.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('OrderItem',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('ref_food_id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('ref_order_id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('test', sa.String(length=64), nullable=True),
                    sa.ForeignKeyConstraint(['ref_food_id'], ['Food.id'], ),
                    sa.ForeignKeyConstraint(['ref_order_id'], ['Order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_index('openid', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('nick_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('avatarUrl', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cashbox', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('openid', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('openid', 'customer', ['openid'], unique=True)
    op.drop_table('OrderItem')
    op.drop_table('Food')
    op.drop_table('Restaurant')
    op.drop_table('Order')
    op.drop_table('Customer')
    # ### end Alembic commands ###
