"""empty message

Revision ID: 48d540210757
Revises: 
Create Date: 2018-09-06 21:45:08.437042

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '48d540210757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Boss',
    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
    sa.Column('nick_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('province', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('avatarUrl', sa.String(length=200), nullable=True),
    sa.Column('cashbox', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('band_card_number', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
    sa.Column('nick_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('province', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('avatarUrl', sa.String(length=200), nullable=True),
    sa.Column('cashbox', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('Boss')
    # ### end Alembic commands ###
