"""add openid

Revision ID: 61df852df07c
Revises: 48d540210757
Create Date: 2018-09-07 09:18:04.494182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61df852df07c'
down_revision = '48d540210757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Boss', sa.Column('openid', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'Boss', ['openid'])
    op.add_column('customer', sa.Column('openid', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'customer', ['openid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'openid')
    op.drop_constraint(None, 'Boss', type_='unique')
    op.drop_column('Boss', 'openid')
    # ### end Alembic commands ###
