"""change structure

Revision ID: f7d34f3c7455
Revises: 61df852df07c
Create Date: 2018-09-07 09:48:06.050924

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import app.models

# revision identifiers, used by Alembic.
revision = 'f7d34f3c7455'
down_revision = '61df852df07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
                    sa.Column('id', app.models.UNSIGNED_INT(unsigned=True), nullable=False),
                    sa.Column('openid', sa.String(length=64), nullable=False),
                    sa.Column('nick_name', sa.String(length=64), nullable=False),
                    sa.Column('gender', sa.Integer(), nullable=True),
                    sa.Column('city', sa.String(length=40), nullable=True),
                    sa.Column('province', sa.String(length=40), nullable=True),
                    sa.Column('country', sa.String(length=40), nullable=True),
                    sa.Column('avatarUrl', sa.String(length=200), nullable=True),
                    sa.Column('cashbox', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('openid')
                    )
    op.drop_index('openid', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('nick_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('avatarUrl', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cashbox', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('openid', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('openid', 'customer', ['openid'], unique=True)
    op.drop_table('Customer')
    # ### end Alembic commands ###
